function(static_link_stl target_name)
  if (MSVC)
    set_target_properties(${target_name} PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
  elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    target_link_libraries(${target_name} PRIVATE -static-libstdc++ -static-libgcc)
  elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    target_link_libraries(${target_name} PRIVATE -static-libstdc++)
  endif()
endfunction()
